const ED = {
  paper: '#f5f1e8',
  card: '#fbf8f1',
  ink: '#1a1612',
  softInk: '#5c4a2f',
  muted: '#8b7e62',
  rule: '#e8e0cf',
  pillBorder: '#d4c9b0',
  warn: '#c2410c',
  warnBg: '#fef3e2',
  warnText: '#9a3412',
  warnDark: '#7c4a03',
  success: '#15803d',
  successBg: '#ecfdf5',
  successText: '#14532d',
  errorBg: '#fef2f2',
  errorText: '#991b1b',
  amber: '#fef3c7',
  amberBorder: '#fbbf24',
  amberText: '#7c4a03',
};

export { ED };

export default {
  light: {
    background: ED.paper,
    backgroundSecondary: '#ede8dc',
    surface: ED.card,
    surfaceElevated: ED.card,
    text: ED.ink,
    textSecondary: ED.softInk,
    textMuted: ED.muted,
    border: ED.rule,
    borderLight: '#ede8dc',
    primary: ED.ink,
    primaryLight: '#2d2420',
    primaryMuted: ED.warnBg,
    accent: ED.warn,
    accentLight: ED.warnBg,
    tint: ED.ink,
    tabIconDefault: ED.muted,
    tabIconSelected: ED.ink,
    likeColor: ED.warn,
    success: ED.success,
    successBg: ED.successBg,
    error: '#dc2626',
    errorBg: ED.errorBg,
    cardBackground: ED.card,
    tag: '#f0ebe0',
    tagText: ED.softInk,
    pillBorder: ED.pillBorder,
  },
  editorial: ED,
};
