// Realistic Ontario university data for oHub
// Grade 12 students applying through OUAC

window.oHubData = {
  user: {
    name: "Priya Shah",
    school: "Bayview Secondary, Richmond Hill",
    avg: 92.4,
    grade: 12,
    ouacRef: "2026-1093478",
    daysToDeadline: 12,
  },

  // OUAC 101 deadline is Jan 15
  keyDates: [
    { label: "OUAC 101 deadline", date: "Jan 15", daysOut: 12, type: "critical" },
    { label: "Waterloo AIF due", date: "Feb 1", daysOut: 29, type: "high" },
    { label: "Western supp. essay", date: "Feb 4", daysOut: 32, type: "high" },
    { label: "Mid-term grades upload", date: "Feb 10", daysOut: 38, type: "med" },
    { label: "Queen's PSE due", date: "Feb 15", daysOut: 43, type: "high" },
    { label: "First offers (early round)", date: "Feb 20", daysOut: 48, type: "info" },
  ],

  universities: [
    { id: "uoft", name: "University of Toronto", short: "U of T", city: "Toronto", color: "#002A5C", initials: "UT" },
    { id: "waterloo", name: "University of Waterloo", short: "Waterloo", city: "Waterloo", color: "#FFD54F", initials: "UW" },
    { id: "western", name: "Western University", short: "Western", city: "London", color: "#4F2683", initials: "W" },
    { id: "queens", name: "Queen's University", short: "Queen's", city: "Kingston", color: "#B9975B", initials: "Q" },
    { id: "mcmaster", name: "McMaster University", short: "Mac", city: "Hamilton", color: "#A6192E", initials: "M" },
    { id: "tmu", name: "Toronto Metropolitan", short: "TMU", city: "Toronto", color: "#005CB9", initials: "TM" },
    { id: "york", name: "York University", short: "York", city: "Toronto", color: "#E31837", initials: "Y" },
    { id: "ottawa", name: "University of Ottawa", short: "uOttawa", city: "Ottawa", color: "#8B1A1A", initials: "uO" },
  ],

  programs: [
    {
      id: "uw-cs",
      uni: "waterloo",
      name: "Computer Science",
      faculty: "Mathematics",
      code: "WTM",
      cutoff: 95,
      avgAdmitted: 96.2,
      coop: true,
      length: "5 years (with co-op)",
      tuition: "$18,940 / yr",
      enrolled: 730,
      acceptance: "7%",
      saved: true,
      applied: true,
      requires: ["AIF (Admission Info Form)", "ENG4U", "MHF4U", "MCV4U", "Calculus & Vectors"],
      essays: 1,
      tier: "reach",
      blurb: "Canada's flagship CS program. Co-op streams place at Google, Stripe, OpenAI.",
      deadlines: [{ label: "OUAC application", date: "Jan 15" }, { label: "AIF", date: "Feb 1" }],
    },
    {
      id: "uoft-engsci",
      uni: "uoft",
      name: "Engineering Science",
      faculty: "Applied Science & Eng.",
      code: "TAES",
      cutoff: 94,
      avgAdmitted: 95.1,
      coop: false,
      length: "4 years",
      tuition: "$17,090 / yr",
      enrolled: 230,
      acceptance: "12%",
      saved: true,
      applied: true,
      requires: ["Supplementary Application", "ENG4U", "MHF4U", "MCV4U", "SPH4U", "SCH4U"],
      essays: 3,
      tier: "reach",
      blurb: "Toronto's most selective undergrad. Specialize in AI, robotics, biomed in year 3.",
      deadlines: [{ label: "OUAC", date: "Jan 15" }, { label: "Supplementary App", date: "Feb 1" }],
    },
    {
      id: "queens-comm",
      uni: "queens",
      name: "Commerce",
      faculty: "Smith School of Business",
      code: "QC",
      cutoff: 92,
      avgAdmitted: 94.0,
      coop: false,
      length: "4 years",
      tuition: "$18,000 / yr",
      enrolled: 500,
      acceptance: "9%",
      saved: true,
      applied: true,
      requires: ["PSE (Personal Statement)", "Supp. Essay", "ENG4U", "MHF4U or MCV4U"],
      essays: 2,
      tier: "target",
      blurb: "Smith Commerce — top-ranked business undergrad in Canada.",
      deadlines: [{ label: "OUAC", date: "Jan 15" }, { label: "PSE", date: "Feb 15" }],
    },
    {
      id: "western-ivey",
      uni: "western",
      name: "Ivey AEO",
      faculty: "Ivey Business School",
      code: "EAB",
      cutoff: 90,
      avgAdmitted: 92.8,
      coop: false,
      length: "4 years (HBA in y3-4)",
      tuition: "$15,700 / yr",
      enrolled: 600,
      acceptance: "15%",
      saved: true,
      applied: false,
      requires: ["Supplementary App", "Video Essay", "ENG4U", "MHF4U"],
      essays: 4,
      tier: "target",
      blurb: "Advanced Entry Opportunity — guaranteed seat at HBA after year 2.",
      deadlines: [{ label: "OUAC", date: "Jan 15" }, { label: "Supplementary", date: "Feb 4" }],
    },
    {
      id: "mac-health",
      uni: "mcmaster",
      name: "Health Sciences",
      faculty: "Faculty of Health Sci.",
      code: "MHS",
      cutoff: 95,
      avgAdmitted: 96.7,
      coop: false,
      length: "4 years",
      tuition: "$7,200 / yr",
      enrolled: 240,
      acceptance: "4.5%",
      saved: true,
      applied: false,
      requires: ["Supplementary App", "ENG4U", "Two 4U sciences", "MHF4U"],
      essays: 3,
      tier: "reach",
      blurb: "Most selective health program in Canada. Pre-med stepping stone.",
      deadlines: [{ label: "OUAC", date: "Jan 15" }, { label: "Supplementary", date: "Jan 17" }],
    },
    {
      id: "uoft-rotman",
      uni: "uoft",
      name: "Rotman Commerce",
      faculty: "Rotman School of Management",
      code: "TRM",
      cutoff: 91,
      avgAdmitted: 93.2,
      coop: false,
      length: "4 years",
      tuition: "$17,090 / yr",
      enrolled: 680,
      acceptance: "20%",
      saved: false,
      applied: true,
      requires: ["Supplementary App", "ENG4U", "MHF4U or MCV4U"],
      essays: 2,
      tier: "target",
      blurb: "Rotman BCom in downtown Toronto. Specializations in Finance, Marketing, Mgmt.",
      deadlines: [{ label: "OUAC", date: "Jan 15" }, { label: "Supplementary", date: "Feb 1" }],
    },
    {
      id: "uw-bba-mathcs",
      uni: "waterloo",
      name: "Math/CS + Laurier BBA",
      faculty: "Double Degree",
      code: "WTM-D",
      cutoff: 90,
      avgAdmitted: 93.5,
      coop: true,
      length: "5 years (with co-op)",
      tuition: "$22,400 / yr",
      enrolled: 100,
      acceptance: "10%",
      saved: false,
      applied: false,
      requires: ["AIF", "Supp. for BBA", "ENG4U", "MHF4U", "MCV4U"],
      essays: 2,
      tier: "target",
      blurb: "Two degrees in five years. Math/CS + Business — hot in fintech.",
      deadlines: [{ label: "OUAC", date: "Jan 15" }, { label: "AIF + BBA Supp", date: "Feb 1" }],
    },
    {
      id: "uoft-cs",
      uni: "uoft",
      name: "Computer Science",
      faculty: "Arts & Science",
      code: "TAS",
      cutoff: 88,
      avgAdmitted: 94.1,
      coop: true,
      length: "4 years (PEY co-op)",
      tuition: "$17,090 / yr",
      enrolled: 800,
      acceptance: "Stream after Y1",
      saved: false,
      applied: true,
      requires: ["ENG4U", "MHF4U", "MCV4U"],
      essays: 0,
      tier: "safety",
      blurb: "Apply to A&S, then stream into CS at end of first year. PEY co-op.",
      deadlines: [{ label: "OUAC", date: "Jan 15" }],
    },
  ],

  applications: {
    submitted: 5,
    drafted: 2,
    total: 7,
    decisions: { accepted: 0, waitlisted: 0, rejected: 0, pending: 5 },
  },

  // Application timeline progress
  appProgress: [
    { uni: "U of T", program: "Engineering Science", status: "Submitted", essays: "3/3", date: "Dec 18" },
    { uni: "U of T", program: "Rotman Commerce", status: "Submitted", essays: "2/2", date: "Dec 18" },
    { uni: "U of T", program: "Computer Science", status: "Submitted", essays: "0/0", date: "Dec 18" },
    { uni: "Waterloo", program: "Computer Science", status: "AIF in progress", essays: "Draft", date: "—" },
    { uni: "Queen's", program: "Commerce", status: "PSE in progress", essays: "1/2", date: "—" },
    { uni: "Western", program: "Ivey AEO", status: "Not started", essays: "0/4", date: "—" },
    { uni: "McMaster", program: "Health Sci", status: "Not started", essays: "0/3", date: "—" },
  ],

  scholarships: [
    { name: "Schulich Leader", value: "$100,000", deadline: "Jan 25", match: 89, status: "Eligible" },
    { name: "Loran Award", value: "$100,000", deadline: "Closed", match: 76, status: "Submitted" },
    { name: "TD Community Leadership", value: "$70,000", deadline: "Closed", match: 82, status: "Submitted" },
    { name: "Queen's Chancellor's", value: "$36,000", deadline: "Auto", match: 95, status: "Auto-considered" },
    { name: "Western National", value: "$40,000", deadline: "Auto", match: 91, status: "Auto-considered" },
    { name: "Waterloo President's", value: "$2,000", deadline: "Auto", match: 88, status: "Auto-considered" },
  ],

  chats: [
    { id: 1, name: "OUAC 101 Class of '26", members: 412, last: "anyone else freaking out about Waterloo AIF??", time: "2m", unread: 12, pinned: true },
    { id: 2, name: "Bayview SS — Y12", members: 87, last: "Ms. Chen wants ref letters by Friday", time: "18m", unread: 3, pinned: true },
    { id: 3, name: "Aanya Patel", members: 2, last: "i submitted ivey 🥲 send help", time: "1h", unread: 1, dm: true },
    { id: 4, name: "Eng Sci Hopefuls", members: 156, last: "Question 3 on Toronto supp — anyone got a structure?", time: "3h", unread: 0 },
    { id: 5, name: "Rishi Mehta", members: 2, last: "you applied to Mac Health?", time: "5h", unread: 0, dm: true },
    { id: 6, name: "Smith Commerce 2030", members: 89, last: "PSE word count question…", time: "1d", unread: 0 },
  ],

  notifications: [
    { type: "deadline", text: "Waterloo AIF due in 29 days", time: "now" },
    { type: "match", text: "New scholarship match: Schulich Leader (89%)", time: "2h" },
    { type: "social", text: "Aanya replied to your essay draft", time: "3h" },
    { type: "system", text: "OUAC reference number confirmed", time: "1d" },
    { type: "deadline", text: "Mid-term grades upload coming up", time: "2d" },
  ],

  todayTasks: [
    { id: 1, label: "Finish Waterloo AIF — Section 3", est: "25 min", done: false, prio: "high" },
    { id: 2, label: "Review Queen's PSE draft with Aanya", est: "15 min", done: false, prio: "med" },
    { id: 3, label: "Email Mr. Patel — ref letter follow-up", est: "5 min", done: true, prio: "low" },
    { id: 4, label: "Practice Ivey video essay (3 takes)", est: "30 min", done: false, prio: "high" },
  ],

  events: [
    { name: "Waterloo Virtual Tour", host: "Waterloo", date: "Tue Jan 14", time: "7 PM", attending: true },
    { name: "Smith PSE Workshop", host: "Queen's", date: "Wed Jan 15", time: "6 PM", attending: false },
    { name: "Toronto Eng Open House", host: "U of T", date: "Sat Jan 18", time: "11 AM", attending: true },
    { name: "Schulich Leader Info Session", host: "Schulich", date: "Mon Jan 20", time: "8 PM", attending: false },
  ],

  feed: [
    { type: "milestone", who: "You", text: "submitted 3 U of T applications", time: "Dec 18" },
    { type: "post", who: "Aanya P.", school: "Bayview SS", text: "anyone with a Waterloo AIF tip? on question 4 and stuck", likes: 12, comments: 8, time: "2h" },
    { type: "tip", who: "oHub Tips", text: "Schools weight your top 6 4U courses. Drop your weakest if you have an extra elective.", saves: 234, time: "4h" },
    { type: "post", who: "Rishi M.", school: "Earl Haig SS", text: "Ivey video essay take 17. someone please tell me to stop.", likes: 89, comments: 24, time: "6h" },
  ],
};
